const packages = [
  // Japan Packages
  {
    id: 'japan-cherry-blossom',
    name: 'Cherry Blossom Special',
    destination: 'japan',
    duration: 10,
    price: 1329,
    originalPrice: 1899,
    discount: 30,
    theme: ['honeymoon', 'family', 'group'],
    season: 'spring',
    emoji: '🌸',
    gradient: 'from-pink-200 to-pink-100',
    description: 'Experience the magical sakura season with visits to Tokyo, Kyoto, and Osaka.',
    highlights: ['Cherry blossom viewing', 'Traditional tea ceremony', 'Mount Fuji visit', 'Bullet train experience']
  },
  {
    id: 'japan-tokyo-kyoto',
    name: 'Tokyo & Kyoto Explorer',
    destination: 'japan',
    duration: 8,
    price: 1599,
    theme: ['family', 'solo', 'group'],
    season: 'all',
    emoji: '🗼',
    gradient: 'from-red-200 to-orange-100',
    description: 'The perfect introduction to Japan - modern Tokyo meets traditional Kyoto.',
    highlights: ['Shibuya crossing', 'Fushimi Inari shrine', 'Geisha district', 'Japanese cuisine tour']
  },
  {
    id: 'japan-adventure',
    name: 'Japan Adventure Trail',
    destination: 'japan',
    duration: 12,
    price: 2299,
    theme: ['solo', 'group'],
    season: 'summer',
    emoji: '🗻',
    gradient: 'from-blue-200 to-sky-100',
    description: 'For thrill-seekers: hiking, skiing, and outdoor adventures across Japan.',
    highlights: ['Mt. Fuji climb', 'Japanese Alps', 'Hot spring experience', 'Ninja training']
  },
  {
    id: 'japan-honeymoon',
    name: 'Romantic Japan',
    destination: 'japan',
    duration: 9,
    price: 2899,
    theme: ['honeymoon'],
    season: 'spring',
    emoji: '💕',
    gradient: 'from-rose-200 to-pink-100',
    description: "Luxury romantic getaway through Japan's most enchanting destinations.",
    highlights: ['Private ryokan stay', "Couple's spa", 'Romantic dinner cruise', 'Private tea ceremony']
  },
  // India Packages
  {
    id: 'india-rajasthan',
    name: 'Royal Rajasthan',
    destination: 'india',
    duration: 10,
    price: 1124,
    originalPrice: 1499,
    discount: 25,
    theme: ['family', 'honeymoon', 'group'],
    season: 'winter',
    emoji: '🏰',
    gradient: 'from-orange-200 to-amber-100',
    description: 'Explore the land of kings - palaces, forts, and desert adventures.',
    highlights: ['Taj Mahal', 'Jaipur Pink City', 'Desert safari', 'Heritage hotel stays']
  },
  {
    id: 'india-golden-triangle',
    name: 'Golden Triangle Classic',
    destination: 'india',
    duration: 7,
    price: 899,
    theme: ['family', 'solo', 'short-break'],
    season: 'all',
    emoji: '🕌',
    gradient: 'from-yellow-200 to-amber-100',
    description: "Delhi, Agra, and Jaipur - India's most iconic destinations.",
    highlights: ['Taj Mahal sunrise', 'Red Fort', 'Amber Fort', 'Local market tours']
  },
  {
    id: 'india-kerala',
    name: 'Kerala Backwaters',
    destination: 'india',
    duration: 8,
    price: 1299,
    theme: ['honeymoon', 'family'],
    season: 'winter',
    emoji: '🛶',
    gradient: 'from-green-200 to-emerald-100',
    description: "Serene houseboat journeys and tropical paradise in God's Own Country.",
    highlights: ['Houseboat cruise', 'Ayurvedic spa', 'Tea plantations', 'Beach time']
  },
  {
    id: 'india-spiritual',
    name: 'Spiritual India Journey',
    destination: 'india',
    duration: 11,
    price: 1599,
    theme: ['solo', 'group'],
    season: 'all',
    emoji: '🧘',
    gradient: 'from-purple-200 to-violet-100',
    description: "A transformative journey through India's spiritual heartland.",
    highlights: ['Varanasi ghats', 'Yoga retreat', 'Meditation sessions', 'Temple visits']
  },
  // Multi-country
  {
    id: 'asia-grand-tour',
    name: 'Grand Asia Explorer',
    destination: 'both',
    duration: 18,
    price: 3999,
    theme: ['multi-country', 'group'],
    season: 'spring',
    emoji: '🌏',
    gradient: 'from-teal-200 to-cyan-100',
    description: 'The ultimate journey: Japan and India in one epic adventure.',
    highlights: ['Tokyo & Kyoto', 'Taj Mahal', 'Cherry blossoms', 'Rajasthan palaces']
  },
  {
    id: 'asia-highlights',
    name: 'Asia Highlights',
    destination: 'both',
    duration: 14,
    price: 2899,
    theme: ['multi-country', 'family'],
    season: 'all',
    emoji: '✨',
    gradient: 'from-indigo-200 to-blue-100',
    description: 'Best of both worlds - highlights of Japan and India combined.',
    highlights: ['Tokyo modern', 'Kyoto traditional', 'Golden Triangle', 'Cultural immersion']
  }
];
